global_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 2.0
  publish_frequency: 5.0
  transform_tolerance: 0.5

  static_map: false

  width: 20
  height: 20
  origin_x: -10
  origin_y: -10
 
